services:

  # GOLANG
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true
  
  #POSTGRES
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      DEBUG: "true"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data

  # PGADMIN
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_converter
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test

volumes:
  external-storage:
    external: true